# Generated by Django 3.2.5 on 2021-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Office', models.CharField(blank=True, max_length=100, null=True)),
                ('Circuit', models.CharField(blank=True, max_length=100, null=True)),
                ('Accessory', models.CharField(blank=True, max_length=100, null=True)),
                ('Case', models.CharField(blank=True, max_length=100, null=True)),
                ('Customer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pathimage', models.CharField(blank=True, max_length=100, null=True)),
                ('pathoraclecloud', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
