# Generated by Django 3.2.5 on 2021-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nameimagenew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='nameimageold',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
