# Generated by Django 3.2.5 on 2021-07-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0002_auto_20210713_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Office',
        ),
    ]
