# Generated by Django 3.2.5 on 2021-07-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0004_auto_20210719_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='accessory',
            new_name='Accessory',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='accessory1',
            new_name='Accessory1',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='accessory2',
            new_name='Accessory2',
        ),
    ]
