# Generated by Django 3.2.5 on 2021-07-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0005_auto_20210719_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Accessory',
            new_name='abnor_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Accessory1',
            new_name='eq_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Day',
            new_name='job_data',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Accessory2',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Case',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Case1',
            new_name='job_officerid',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='pathoraclecloud',
            new_name='job_picture',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Time',
            new_name='job_time',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Case2',
            new_name='subeq_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='vol_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Category1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Category2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Circuit',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Customer_number',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pathimage',
        ),
    ]
