# Generated by Django 3.2.5 on 2021-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0006_auto_20210723_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pathimage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
