# Generated by Django 3.2.5 on 2021-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0007_image_pathimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='abnor_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
